# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_of_payment', models.DateField(default='2017-01-01')),
                ('loan_total', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('term_AY', models.CharField(default='Term 1, AY17-18', max_length=15)),
                ('start_of_term', models.DateField(default='2017-01-01')),
                ('end_of_term', models.DateField(default='2017-01-01')),
                ('application_start', models.DateField(default='2017-01-01')),
                ('application_end', models.DateField(default='2017-01-01')),
                ('release_of_results', models.DateField(default='2017-01-01')),
                ('all_notified', models.BooleanField(default=False)),
            ],
        ),
    ]
