# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='application_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='info',
            name='application_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='info',
            name='end_of_term',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='info',
            name='release_of_results',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='info',
            name='start_of_term',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
