# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='In Process', max_length=10)),
                ('balance', models.FloatField(default=0)),
                ('term_AY', models.CharField(max_length=15)),
                ('maturity_date', models.DateField(default='2017-01-01')),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orNum', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('isApproved', models.BooleanField(default=False)),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
    ]
