# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='notif_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(),
        ),
    ]
