# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20171207_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(default='2017-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term_AY',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
