# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('student', '0003_auto_20171210_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_times', models.IntegerField()),
                ('sex', models.CharField(max_length=6)),
                ('civil_status', models.CharField(max_length=7)),
                ('citizenship', models.CharField(max_length=20)),
                ('remaining_terms', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('birthday', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=1000)),
                ('f_name', models.CharField(max_length=100)),
                ('f_home_address', models.CharField(max_length=1000)),
                ('f_occupation', models.CharField(max_length=20)),
                ('f_office_address', models.CharField(max_length=1000)),
                ('f_cellphone_number', models.CharField(blank=True, max_length=11)),
                ('m_name', models.CharField(max_length=100)),
                ('m_home_address', models.CharField(max_length=1000)),
                ('m_occupation', models.CharField(max_length=20)),
                ('m_office_address', models.CharField(max_length=1000)),
                ('m_cellphone_number', models.CharField(blank=True, max_length=11)),
                ('g_name', models.CharField(max_length=100)),
                ('g_address', models.CharField(max_length=1000)),
                ('g_occupation', models.CharField(max_length=20)),
                ('g_office_address', models.CharField(max_length=1000)),
                ('g_cellphone_number', models.CharField(blank=True, max_length=11)),
                ('amt_words', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=2000)),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(default='2017-01-01'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term_AY',
            field=models.CharField(max_length=15),
        ),
    ]
