# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20171215_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='amt_num',
            field=models.FloatField(default=0),
        ),
    ]
