# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_application_amt_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id_number',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
